### ISSUE TITLE
Magento 1.9.2.2

### ISSUE THREAD

**Issue by michel1986** [aurmil/magento-cleanup-session#1]
Hello,

is the extension also working on Magento 1.9.2.2.?

best regards,
Michel

**Comment by aurmil** [comment]
hello,

It was tested on an earlier 1.9 version so it should work on 1.9.2.2, yes

I'll try to test it tomorrow on a VM

regards

**Comment by aurmil** [comment]
I can confirm that it absolutely works on 1.9.2.2
regards
